# -*- coding: utf-8 -*-
"""Actividad_9_ClasificacionMulticlase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pSdTY4fEguW12XAsm4St9VsOBFikmVSK
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

data = pd.read_csv('Sensor.csv')
#print(data)

x = np.asanyarray(data.drop(columns=['D']))
y = np.asanyarray(data[['D']])

xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2)

ytrain = keras.utils.to_categorical(ytrain,9)
ytest = keras.utils.to_categorical(ytest,9)

model = Sequential()

model.add(Dense(32,activation='relu',input_shape=[x.shape[1]]))
model.add(Dense(16,activation='relu'))
model.add(Dense(9,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

hist = model.fit(xtrain,ytrain,batch_size=10,epochs=150,verbose=0,validation_data=(xtest,ytest))

plt.figure()
plt.grid()
plt.plot(hist.history['loss'],lw=2)
plt.plot(hist.history['val_loss'],lw=2)
plt.title('Model loss')
plt.xlabel('loss')
plt.ylabel('epoch')
plt.legend(['train','test'])
plt.show()

plt.figure()
plt.grid()
plt.plot(hist.history['accuracy'],lw=2)
plt.plot(hist.history['val_accuracy'],lw=2)
plt.title('Model accuracy')
plt.xlabel('accuracy')
plt.ylabel('epoch')
plt.legend(['train','test'])
plt.show()

ypred = model.predict(x)
ypred = np.argmax(ypred,axis=1)

print('\nMétricas: \n', classification_report(y,ypred));

print('Matriz de confusión: \n', confusion_matrix(y,ypred))